# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3545c0c92acf3a6e089f780320768d2f6c6e8b3483c637e6be36cb1e889e3b74fc9e3ad0340ac8c1dc2b199fc4eb809edabdb47ee636f152c7d12e42cd8b57f7

test:
  secret_key_base: f16f1534799bbd13b60c3b20a7299ed196268a17e3de7bd0ec4d5671515c3462ed699167175a5ab4db69f93e2514cf31d8e0d616fcfa545602a04b693d8c182d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
